### ISSUE TITLE
.jpg extension not added to the end of the URL

### ISSUE THREAD

**Issue by Kiina** [onliner/imgproxy-php#4]
When I set my type to webp I get a result like this:

`T13TPN6_y57OVGopJCEzErIidgp_CE17QGFe9AIuwVI/q:90/w:500/h:500/sm:1/el:0/czM6Ly9tZW5zZmFz/aGlvbi9rYXRlZ29y/aWVfaG9zZW4uanBn.webp`

Same with png:
                                        
`KBlSYOPErBPY9QzSq1utGqvjKxWSbH105P3VPROBk/q:90/w:500/h:500/sm:1/el:0/czM6Ly9tZW5zZmFz/aGlvbi9rYXRlZ29y/aWVfaG9zZW4uanBn.png`

But when it's set to jpg I get this:
                                       
`MscjM8s6aSH-QVWizO_zzDyaphROHKZzOEZXjGRBfw/q:90/w:500/h:500/sm:1/el:0/czM6Ly9tZW5zZmFz/aGlvbi9rYXRlZ29y/aWVfaG9zZW4uanBn`
   
As you can see the extension isn't added. Weirdly enough if I set it to jpeg with an e I get the following URL:

`4tD0SJyccMz-bC-NImnBASRrI96g9xsHQOYQflF59T8/q:90/w:500/h:500/sm:1/el:0/czM6Ly9tZW5zZmFz/aGlvbi9rYXRlZ29y/aWVfaG9zZW4uanBn.jpeg`

I would really like at least an option to always include the extension so I can always see what type was set.

**Comment by mohorev** [comment]
Hi @Kiina. Can you provide an example of your code to reproduce this behaviour?

**Comment by Kiina** [comment]
```php
<?php

require __DIR__ . '/vendor/autoload.php';

use Onliner\ImgProxy\Options\Enlarge;
use Onliner\ImgProxy\Options\StripMetadata;
use Onliner\ImgProxy\UrlBuilder;
use Onliner\ImgProxy\Options\Quality;
use Onliner\ImgProxy\Options\Height;
use Onliner\ImgProxy\Options\Width;

function getImgProxyImages($src, $width, $height, $type): string
{
    $key = getenv('IMG_PROXY_KEY');
    $salt = getenv('IMG_PROXY_SALT');

    $builder = UrlBuilder::signed($key, $salt);
    $builder = $builder->with(
        new Quality(80),
        new Width($width),
        new Height($height),
        new StripMetadata(),
        new Enlarge(false)
    );

    $url = $builder->url($src, $type);

    return $url;
}

//Matching input and output filetype
echo(getImgProxyImages("s3://test/test.jpg", 200, 200, "jpg")."\r\n");
echo(getImgProxyImages("s3://test/test.webp", 200, 200, "webp")."\r\n");

//different input and output filetype
echo(getImgProxyImages("s3://test/test.jpg", 200, 200, "jpeg")."\r\n");
echo(getImgProxyImages("s3://test/test.jpg", 200, 200, "webp")."\r\n");
```
Results in:
```
/9CZYqkUWLKmhETwcXVGawKFjHkSf3H5lXN3eM9UamMM/q:80/w:200/h:200/el:0/czM6Ly90ZXN0L3Rl/c3QuanBn
/C1YtRvHf-jOo_BNmwjl-j-Aeo_BfDv0ieVdPnTDw6qI/q:80/w:200/h:200/el:0/czM6Ly90ZXN0L3Rl/c3Qud2VicA
/EB1hWnCpEydSi0oUnlVVMOEyqQSHMURdQTQ0KuNbLC4/q:80/w:200/h:200/el:0/czM6Ly90ZXN0L3Rl/c3QuanBn.jpeg
/5J0Ba-VtiFYfxDc9WnqKB0URm80LtgZiEGcx3rtb9Ts/q:80/w:200/h:200/el:0/czM6Ly90ZXN0L3Rl/c3QuanBn.webp
```

on the other hand the python handler from https://github.com/klen/imgproxy:

```python
from imgproxy import ImgProxy
import os

s3url = 's3://test/test.jpg'

url = ImgProxy(
    s3url,
    proxy_host='https://test',
    width=200,
    height=200,
    gravity='no',
    enlarge=False,
    resizing_type='auto',
    extension="jpg",
    key=os.getenv("IMG_PROXY_KEY"), 
    salt=os.getenv("IMG_PROXY_SALT")
)

print(url)
```

gets an URL like:

`/YPiFgjRjy0kFm1IunHykPwOk-mldZNpRqD0kXqiR_-0/g:no/rs:auto:200:200:0/czM6Ly90ZXN0L3Rlc3QuanBn.jpg`

even with the input and output format matching.

**Comment by mohorev** [comment]
@Kiina Thanks. Now I understand what you want. Can we find a compromise, let's just do it for encrypted links?
And this will only work for the new release and only in PHP 8.
I hope this can help in your case.

**Comment by mohorev** [comment]
New version [v0.2.1](https://github.com/onliner/imgproxy-php/releases/tag/v0.2.1) released.

**Comment by Kiina** [comment]
Perfect, seems to work as expected! Thank you
